### ISSUE TITLE
seems unnecessary replace usage left in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [brancz/prometheus-example-app#13]
It seems that module `github.com/brancz/prometheus-example-app` at now directly depends on `v1.3.0` of `github.com/prometheus/client_golang`. <br>
<https://github.com/brancz/prometheus-example-app/blob/master/go.mod#L6>
```txt
github.com/prometheus/client_golang v1.3.0
```
So, replace usage left in go.mod makes no sense. Should it be dropped? <br>
<https://github.com/brancz/prometheus-example-app/blob/master/go.mod#L10>
```txt
replace github.com/prometheus/client_golang => github.com/prometheus/client_golang v1.3.0
```

**Comment by brancz** [comment]
Huh I don’t even understand how that got there. Absolutely! Do you want to open a PR to remove it?

**Comment by Morty-luo** [comment]
Simply run `go mod edit -dropreplace=github.com/prometheus/client_golang` should be able to remove it.
