### ISSUE TITLE
The README document does not specify which metrics are exposed

### ISSUE THREAD

**Issue by pgodowski** [brancz/prometheus-example-app#9]
This sample Prometheus app is great and it extremely useful for any newcomer to Prometheus.
It would be very useful to have the landing page to mention which metrics are actually exposed by this application, without actually having it deployed and looking into Prometheus collected data.
In case something goes wrong, or for the user who is just starting with Prometheus, there is no information what data to look for.

This issue might be amplified given that OpenShift 4.6 refers to this application as an example app for user workload monitoring.

I can submit a PR with the proposed doc changes.

References: https://docs.openshift.com/container-platform/4.6/monitoring/managing-metrics.html

**Comment by pgodowski** [comment]
Added PR to resolve this issue: https://github.com/brancz/prometheus-example-app/pull/10

@brancz can you please review?

**Comment by brancz** [comment]
Closed by #10

**Comment by brancz** [comment]
Thank you for the contribution! :)
